// Nombres de empresas para mostrar junto al ticker.
export const STOCK_NAMES: Record<string, string> = {
  ALUA: 'Aluar', BBAR: 'BBVA Argentina', BMA: 'Banco Macro', BYMA: 'BYMA', CEPU: 'Central Puerto', COME: 'Soc. Comercial del Plata',
  CRES: 'Cresud', EDN: 'Edenor', GGAL: 'Grupo Galicia', IRSA: 'IRSA', LOMA: 'Loma Negra', METR: 'Metrogas', PAMP: 'Pampa Energía',
  SUPV: 'Supervielle', TECO2: 'Telecom', TGNO4: 'TGN', TGSU2: 'TGS', TRAN: 'Transener', TXAR: 'Ternium Argentina', VALO: 'Grupo Financiero Valores',
  YPFD: 'YPF', AGRO: 'Agrometal', AUSO: 'Autopistas del Sol', BHIP: 'Banco Hipotecario', BOLT: 'Boldt', BPAT: 'Banco Patagonia', CADO: 'Carlos Casado',
  CAPX: 'Capex', CARC: 'Carboclor', CECO2: 'Central Costanera', CELU: 'Celulosa Argentina', CGPA2: 'Camuzzi Gas Pampeana', CTIO: 'Consultatio',
  CVH: 'Cablevisión Holding', DGCU2: 'Distribuidora Gas Cuyana', DOME: 'Domec', ECOG: 'Ecogas', FERR: 'Ferrum', FIPL: 'Fiplasto',
  GAMI: 'B-Gaming', GARO: 'Garovaglio y Zorraquín', GBAN: 'Naturgy BAN', GCDI: 'GCDI', GCLA: 'Grupo Clarín', GRIM: 'Grimoldi', HARG: 'Holcim Argentina',
  HAVA: 'Havanna', INTR: 'Compañía Introductora', INVJ: 'Inversora Juramento',
  LEDE: 'Ledesma', LONG: 'Longvie', MIRG: 'Mirgor', MOLA: 'Molinos Agro', MOLI: 'Molinos Río de la Plata', MORI: 'Morixe', OEST: 'Autopistas del Oeste',
  PATA: 'Importadora Patagonia', POLL: 'Polledo', REGE: 'García Reguera', RICH: 'Laboratorios Richmond', RIGO: 'Rigolleau',
  ROSE: 'Instituto Rosenbusch', SAMI: 'San Miguel', SEMI: 'Molinos Juan Semino', A3: 'A3 Mercados',
};

export const ADR_NAMES: Record<string, string> = {
  YPF: 'YPF', GGAL: 'Grupo Galicia', BMA: 'Banco Macro', PAM: 'Pampa Energía', TGS: 'TGS', CEPU: 'Central Puerto', EDN: 'Edenor', LOMA: 'Loma Negra',
  SUPV: 'Supervielle', BBAR: 'BBVA Argentina', TEO: 'Telecom', CRESY: 'Cresud', IRS: 'IRSA', TX: 'Ternium', TS: 'Tenaris', MELI: 'Mercado Libre',
  GLOB: 'Globant', VIST: 'Vista Energy', DESP: 'Despegar', BIOX: 'Bioceres', CAAP: 'Corporación América',
};

/** ETFs disponibles como CEDEAR, agrupados por tipo. El orden es el de la tabla. */
export const ETF_GROUPS = ['Índices de EE.UU.', 'Sectores de EE.UU.', 'Emergentes e internacional', 'Materias primas', 'Cripto', 'Temáticos'] as const;
export type EtfGroup = (typeof ETF_GROUPS)[number];

export const ETF_INFO: Record<string, [name: string, group: EtfGroup]> = {
  SPY: ['S&P 500', 'Índices de EE.UU.'],
  QQQ: ['Nasdaq 100', 'Índices de EE.UU.'],
  DIA: ['Dow Jones', 'Índices de EE.UU.'],
  IWM: ['Russell 2000 (pymes)', 'Índices de EE.UU.'],
  XLK: ['Tecnología', 'Sectores de EE.UU.'],
  SMH: ['Semiconductores', 'Sectores de EE.UU.'],
  XLF: ['Financiero', 'Sectores de EE.UU.'],
  XLE: ['Energía', 'Sectores de EE.UU.'],
  XLV: ['Salud', 'Sectores de EE.UU.'],
  XLI: ['Industrial', 'Sectores de EE.UU.'],
  XLP: ['Consumo básico', 'Sectores de EE.UU.'],
  XLY: ['Consumo discrecional', 'Sectores de EE.UU.'],
  XLU: ['Servicios públicos', 'Sectores de EE.UU.'],
  XLB: ['Materiales', 'Sectores de EE.UU.'],
  XLC: ['Comunicaciones', 'Sectores de EE.UU.'],
  XLRE: ['Inmobiliario', 'Sectores de EE.UU.'],
  EEM: ['Mercados emergentes', 'Emergentes e internacional'],
  IEMG: ['Emergentes (amplio)', 'Emergentes e internacional'],
  EWZ: ['Brasil', 'Emergentes e internacional'],
  ILF: ['América Latina', 'Emergentes e internacional'],
  FXI: ['China', 'Emergentes e internacional'],
  EWJ: ['Japón', 'Emergentes e internacional'],
  EWY: ['Corea del Sur', 'Emergentes e internacional'],
  IEUR: ['Europa', 'Emergentes e internacional'],
  VEA: ['Desarrollados sin EE.UU.', 'Emergentes e internacional'],
  EFA: ['Europa, Asia y Oceanía', 'Emergentes e internacional'],
  ACWI: ['Mundo', 'Emergentes e internacional'],
  GLD: ['Oro', 'Materias primas'],
  SLV: ['Plata', 'Materias primas'],
  GDX: ['Mineras de oro', 'Materias primas'],
  COPX: ['Mineras de cobre', 'Materias primas'],
  USO: ['Petróleo', 'Materias primas'],
  IBIT: ['Bitcoin (iShares)', 'Cripto'],
  ETHA: ['Ethereum (iShares)', 'Cripto'],
  ARKK: ['ARK Innovation', 'Temáticos'],
};

export const CEDEAR_NAMES: Record<string, string> = {
  ...Object.fromEntries(Object.entries(ETF_INFO).map(([k, [n]]) => [k, `ETF ${n}`])),
  AAPL: 'Apple', MSFT: 'Microsoft', GOOGL: 'Alphabet (Google)', AMZN: 'Amazon', NVDA: 'Nvidia', META: 'Meta', TSLA: 'Tesla', MELI: 'Mercado Libre',
  KO: 'Coca-Cola', PEP: 'PepsiCo', BRKB: 'Berkshire Hathaway', JPM: 'JPMorgan', BAC: 'Bank of America', C: 'Citigroup', WFC: 'Wells Fargo', GS: 'Goldman Sachs',
  MS: 'Morgan Stanley', V: 'Visa', MA: 'Mastercard', PYPL: 'PayPal', AXP: 'American Express', NU: 'Nu Holdings (Nubank)', HOOD: 'Robinhood', SCHW: 'Charles Schwab',
  BLK: 'BlackRock', WMT: 'Walmart', COST: 'Costco', TGT: 'Target', HD: 'Home Depot', MCD: "McDonald's", SBUX: 'Starbucks', NKE: 'Nike', DISN: 'Disney',
  NFLX: 'Netflix', SPOT: 'Spotify', AMD: 'AMD', INTC: 'Intel', AVGO: 'Broadcom', TSM: 'TSMC', ASML: 'ASML', QCOM: 'Qualcomm', MU: 'Micron', ARM: 'Arm Holdings',
  SNDK: 'SanDisk', TXN: 'Texas Instruments', MRVL: 'Marvell', SMCI: 'Super Micro', ORCL: 'Oracle', CRM: 'Salesforce', ADBE: 'Adobe', IBM: 'IBM', CSCO: 'Cisco',
  NOW: 'ServiceNow', SHOP: 'Shopify', SNOW: 'Snowflake', CRWD: 'CrowdStrike', PANW: 'Palo Alto Networks', NET: 'Cloudflare', DELL: 'Dell', HPQ: 'HP',
  BABA: 'Alibaba', JD: 'JD.com', PDD: 'PDD (Temu)', BIDU: 'Baidu', NIO: 'NIO', XPEV: 'XPeng', SE: 'Sea Limited', SONY: 'Sony', TM: 'Toyota',
  PBR: 'Petrobras', VALE: 'Vale', ITUB: 'Itaú', BBD: 'Bradesco', ERJ: 'Embraer', STNE: 'StoneCo', PAGS: 'PagSeguro', XP: 'XP Inc.',
  VIST: 'Vista Energy', GLOB: 'Globant', BIOX: 'Bioceres', SATL: 'Satellogic', DESP: 'Despegar', ARCO: 'Arcos Dorados',
  XOM: 'ExxonMobil', CVX: 'Chevron', OXY: 'Occidental', SLB: 'SLB (Schlumberger)', HAL: 'Halliburton', SHEL: 'Shell', BP: 'BP', COP: 'ConocoPhillips',
  PFE: 'Pfizer', JNJ: 'Johnson & Johnson', MRK: 'Merck', ABBV: 'AbbVie', LLY: 'Eli Lilly', NVO: 'Novo Nordisk', UNH: 'UnitedHealth', AZN: 'AstraZeneca',
  BMY: 'Bristol-Myers Squibb', MRNA: 'Moderna', GILD: 'Gilead', ABT: 'Abbott', AMGN: 'Amgen',
  COIN: 'Coinbase', MSTR: 'Strategy', MARA: 'MARA Holdings', RIOT: 'Riot Platforms', UBER: 'Uber', ABNB: 'Airbnb', PLTR: 'Palantir', RBLX: 'Roblox',
  BA: 'Boeing', CAT: 'Caterpillar', DE: 'John Deere', GE: 'GE Aerospace', MMM: '3M', LMT: 'Lockheed Martin', RTX: 'RTX', HON: 'Honeywell', UPS: 'UPS',
  F: 'Ford', GM: 'General Motors', RACE: 'Ferrari', T: 'AT&T', VZ: 'Verizon', TMUS: 'T-Mobile', PG: 'Procter & Gamble', UL: 'Unilever', MO: 'Altria',
  PM: 'Philip Morris', BRFS: 'BRF', GOLD: 'Barrick Gold', NEM: 'Newmont', FCX: 'Freeport-McMoRan', RIO: 'Rio Tinto', BHP: 'BHP', AAL: 'American Airlines',
  ZM: 'Zoom', SNAP: 'Snap', PINS: 'Pinterest', ETSY: 'Etsy', EBAY: 'eBay', LRCX: 'Lam Research', AMAT: 'Applied Materials', ADI: 'Analog Devices',
  CEG: 'Constellation Energy', VST: 'Vistra', OKLO: 'Oklo', RGTI: 'Rigetti', IONQ: 'IonQ', HMY: 'Harmony Gold', AU: 'AngloGold', SID: 'CSN', GGB: 'Gerdau',
  LAC: 'Lithium Americas', ALB: 'Albemarle', SQM: 'SQM', AVY: 'Avery Dennison', KMB: 'Kimberly-Clark', CL: 'Colgate-Palmolive',
};
